services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ../Dd2WPGKz/train_team_track.parquet:/app/app/data/train_team_track.parquet:ro
      - ./backend/app/data/submission.csv:/app/app/data/submission.csv:ro
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
