"""
Forecast service.

In mock mode (no live model): reads pre-computed submission CSV
and returns predictions for a given route at a given time.

The submission CSV was generated by H41b stack and contains predictions
for the test window (2025-05-30 11:00–15:30).

For simulation at other timestamps we interpolate from train data
using a simple rolling mean as a fallback.
"""

import pandas as pd
import numpy as np
from datetime import datetime

from .data_loader import get_submission, get_train, get_all_route_ids
from .simulator import get_current_time
from ..models.schemas import ForecastStep, ForecastResponse

STEP_MINUTES = 30
N_STEPS = 10


def _rolling_forecast(route_id: int, inference_ts: pd.Timestamp) -> list[float]:
    """
    Simple fallback forecast: use rolling mean of last 48 points
    as a flat forecast for all 10 steps.
    Adds slight hour-of-day scaling from historical patterns.
    """
    train = get_train()
    hist = train[
        (train["route_id"] == route_id) &
        (train["timestamp"] <= inference_ts)
    ].tail(48)

    if len(hist) == 0:
        return [0.0] * N_STEPS

    base = float(hist["target_2h"].mean())

    # Hour-of-day scaling: compute mean target_2h per hour from full history
    route_data = train[train["route_id"] == route_id].copy()
    route_data["hour"] = route_data["timestamp"].dt.hour
    hourly_means = route_data.groupby("hour")["target_2h"].mean()
    global_mean = float(route_data["target_2h"].mean()) or 1.0

    preds = []
    for step in range(1, N_STEPS + 1):
        future_ts = inference_ts + pd.Timedelta(minutes=STEP_MINUTES * step)
        hour = future_ts.hour
        scale = hourly_means.get(hour, global_mean) / global_mean
        preds.append(max(0.0, round(base * scale, 2)))

    return preds


def get_forecast(route_id: int, inference_ts: pd.Timestamp | None = None) -> ForecastResponse:
    if inference_ts is None:
        inference_ts = get_current_time()

    # Try to use submission CSV predictions
    # Submission covers 2025-05-30 11:00–15:30, step 1..10
    sub = get_submission()

    # Check if submission has route_id and step columns (pre-joined format)
    if "route_id" in sub.columns and "step" in sub.columns:
        route_sub = sub[sub["route_id"] == route_id].sort_values("step")
        if len(route_sub) == N_STEPS:
            steps = []
            for _, row in route_sub.iterrows():
                step = int(row["step"])
                ts = inference_ts + pd.Timedelta(minutes=STEP_MINUTES * step)
                steps.append(ForecastStep(
                    step=step,
                    timestamp=ts,
                    y_pred=round(float(row["y_pred"]), 2)
                ))
            return ForecastResponse(
                route_id=route_id,
                inference_timestamp=inference_ts,
                predictions=steps
            )

    # Fallback: rolling mean forecast
    preds = _rolling_forecast(route_id, inference_ts)
    steps = []
    for i, pred in enumerate(preds):
        step = i + 1
        ts = inference_ts + pd.Timedelta(minutes=STEP_MINUTES * step)
        steps.append(ForecastStep(step=step, timestamp=ts, y_pred=pred))

    return ForecastResponse(
        route_id=route_id,
        inference_timestamp=inference_ts,
        predictions=steps
    )


def get_all_forecasts(inference_ts: pd.Timestamp | None = None) -> list[ForecastResponse]:
    if inference_ts is None:
        inference_ts = get_current_time()
    route_ids = get_all_route_ids()
    return [get_forecast(rid, inference_ts) for rid in route_ids]
